apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-dev
  namespace: flask-todo
spec:
  selector:
    matchLabels:
      app: flask-todo-dev
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-todo-dev
    spec:
      containers:
      - name: flask-todo-dev
        image: todok8sacr25hjk3.azurecr.io/flasktodo:dev
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "40m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
          - containerPort: 5000
     
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-secret-provider"
          