apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret-provider
  namespace: flask-todo
spec:
  parameters:
    cloudName: ""
    keyvaultName: todo-k8s-kv
    objects: |
      array:
        - |
          objectName: db-name
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: db-server
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: ai-connection-string
          objectType: secret
          objectVersion: ""
          
    tenantId: a74f56de-5a8c-405e-aafb-905a81b3c861
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
  provider: azure
