apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo
spec:
  selector:
    matchLabels:
      app: flask-todo
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
      - name: flask-todo
        image: bialekpl/flasktodo:1.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
            readOnly: true
        ports:
        - containerPort: 5000
      volumes:
        - name: secret-volume
          secret:
            secretName: db-credentials
