apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}-{{ .Values.env }}
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
