name: Docker build and push to ACR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  DeployDev:  
    name:  "[DEV] Build and push Docker image"
    runs-on: ubuntu-latest
    if: github.event == 'pull_request'
    environment:
      name: dev
    steps:  
    - uses: Azure/docker-login@v1.0.1
      with:
        # Container registry username
        username: ${{ secrets.REGISTRY_USERNAME }}
        # Container registry password
        password: ${{ secrets.REGISTRY_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      
    - uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flasktodo:dev

  DeployStaging:
    name: "[STAGE] Build and push Docker image"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # after merging pull request / pushing to main
    environment:
      name: stage
    steps:  
    - uses: Azure/docker-login@v1.0.1
      with:
        # Container registry username
        username: ${{ secrets.REGISTRY_USERNAME }}
        # Container registry password
        password: ${{ secrets.REGISTRY_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      
    - uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flasktodo:stage
      
  DeployProd:  
    name: "[PROD] Build and push Docker image"
    runs-on: ubuntu-latest
    needs: [DeployStaging]
    environment:
      name: prod
    steps:  
    - uses: Azure/docker-login@v1.0.1
      with:
        # Container registry username
        username: ${{ secrets.REGISTRY_USERNAME }}
        # Container registry password
        password: ${{ secrets.REGISTRY_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      
    - uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/flasktodo:prod
